name: night_break
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pocketbase: ^0.18.1
  shimmer: ^3.0.0
  html: ^0.15.4
  http: ^1.2.0
  provider: ^6.1.1
  get_it: ^7.6.7
  flutter_secure_storage: ^9.0.0
  material_symbols_icons: ^4.2762.0
  flutter_shaders: ^0.1.2

assets:
  - assets/fonts/
  - assets/shaders/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/flame_shader.frag
    - assets/shaders/sand.frag
