name: night_break
description: "A community mindfulness app"
publish_to: "none"
version: 1.0.2

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pocketbase: ^0.18.1
  shimmer: ^3.0.0
  html: ^0.15.4
  http: ^1.2.0
  provider: ^6.1.1
  get_it: ^7.6.7
  flutter_secure_storage: ^9.0.0
  material_symbols_icons: ^4.2762.0
  flutter_shaders: ^0.1.2
  audioplayers: ^6.0.0
  intl: ^0.19.0
  url_launcher: ^6.3.0

assets:
  - assets/fonts/
  - assets/shaders/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/flame_shader.frag
    - assets/shaders/sand.frag

  assets:
    - assets/audio/

flutter_native_splash:
  color: "#000000"
  android_12:
    color: "#000000"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#080803"
  adaptive_icon_foreground: "assets/icon2.png"
