name: night_break
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pocketbase: ^0.18.1
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  html: ^0.15.4
  http: ^1.2.0
  provider: ^6.1.1
  get_it: ^7.6.7
  flutter_secure_storage: ^9.0.0

assets:
  - assets/fonts/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
